#!/usr/bin/env bash
#
# Bootstraps the Netherlands (exit-hop) VM.
# Idempotent: re-running on the same host refreshes the config + restarts
# the container, but does NOT regenerate keys unless you delete .env first.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=../scripts/common.sh
source "$REPO_ROOT/scripts/common.sh"

require_root

log_info "=== Netherlands VM bootstrap ==="

install_docker
ensure_pkg gettext-base envsubst
ensure_pkg jq
ensure_pkg qrencode
ensure_pkg uuid-runtime uuidgen
ensure_pkg openssl
ensure_pkg curl

# Load existing .env on re-runs so we don't regenerate secrets unnecessarily.
if [[ -f $HERE/.env ]]; then
  log_info "reusing existing $HERE/.env (delete it to regenerate keys)"
  set -o allexport; # shellcheck disable=SC1091
  source "$HERE/.env"
  set +o allexport
fi

if [[ -z ${NL_REALITY_PRIVKEY:-} || -z ${NL_REALITY_PUBKEY:-} ]]; then
  log_info "generating Reality keypair"
  generate_reality_keypair
  NL_REALITY_PRIVKEY="$REALITY_PRIVKEY"
  NL_REALITY_PUBKEY="$REALITY_PUBKEY"
fi

: "${NL_USER_UUID:=$(generate_uuid)}"
: "${NL_SHORT_ID:=$(generate_short_id)}"
: "${NL_SERVER_IP:=$(detect_public_ip)}"

export NL_USER_UUID NL_SHORT_ID NL_SERVER_IP NL_REALITY_PRIVKEY NL_REALITY_PUBKEY

cat >"$HERE/.env" <<EOF
# Netherlands VM — generated by bootstrap.sh. Keep secret.
NL_SERVER_IP=$NL_SERVER_IP
NL_USER_UUID=$NL_USER_UUID
NL_SHORT_ID=$NL_SHORT_ID
NL_REALITY_PRIVKEY=$NL_REALITY_PRIVKEY
NL_REALITY_PUBKEY=$NL_REALITY_PUBKEY
EOF
chmod 600 "$HERE/.env"

log_info "rendering sing-box config"
mkdir -p "$HERE/cache"
render_template "$HERE/config/config.json.tmpl" "$HERE/config/config.json"
chmod 600 "$HERE/config/config.json"

open_port_443

log_info "starting sing-box"
(cd "$HERE" && docker compose up -d)

# Wait briefly and check the container is healthy.
sleep 2
if ! (cd "$HERE" && docker compose ps --status running | grep -q sing-box); then
  (cd "$HERE" && docker compose logs --tail 50 sing-box)
  die "sing-box failed to start"
fi

cat >"$HERE/deployment-info.txt" <<EOF
# Paste these into the Russia bootstrap:
NL_SERVER_IP=$NL_SERVER_IP
NL_REALITY_PUBKEY=$NL_REALITY_PUBKEY
NL_USER_UUID=$NL_USER_UUID
NL_SHORT_ID=$NL_SHORT_ID
EOF
chmod 600 "$HERE/deployment-info.txt"

log_ok "Netherlands VM is live on :443"
echo
echo "------- Russia bootstrap flags -------"
echo "sudo bash bootstrap.sh \\"
echo "  --nl-ip       $NL_SERVER_IP \\"
echo "  --nl-pubkey   $NL_REALITY_PUBKEY \\"
echo "  --nl-uuid     $NL_USER_UUID \\"
echo "  --nl-short-id $NL_SHORT_ID"
echo "--------------------------------------"
echo "(also saved to $HERE/deployment-info.txt)"
