#!/usr/bin/env bash
#
# Bootstraps the Exit-hop VM.
# Idempotent: re-running on the same host refreshes the config + restarts
# the container, but does NOT regenerate keys unless you delete .env first.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=../scripts/common.sh
source "$REPO_ROOT/scripts/common.sh"

require_root

log_info "=== Exit VM bootstrap ==="

install_docker
ensure_pkg gettext-base envsubst
ensure_pkg jq
ensure_pkg qrencode
ensure_pkg uuid-runtime uuidgen
ensure_pkg openssl
ensure_pkg curl

# Load existing .env on re-runs so we don't regenerate secrets unnecessarily.
if [[ -f $HERE/.env ]]; then
  log_info "reusing existing $HERE/.env (delete it to regenerate keys)"
  set -o allexport; # shellcheck disable=SC1091
  source "$HERE/.env"
  set +o allexport
fi

if [[ -z ${EXIT_REALITY_PRIVKEY:-} || -z ${EXIT_REALITY_PUBKEY:-} ]]; then
  log_info "generating Reality keypair"
  generate_reality_keypair
  EXIT_REALITY_PRIVKEY="$REALITY_PRIVKEY"
  EXIT_REALITY_PUBKEY="$REALITY_PUBKEY"
fi

: "${EXIT_USER_UUID:=$(generate_uuid)}"
: "${EXIT_SHORT_ID:=$(generate_short_id)}"
: "${EXIT_SERVER_IP:=$(detect_public_ip)}"

export EXIT_USER_UUID EXIT_SHORT_ID EXIT_SERVER_IP EXIT_REALITY_PRIVKEY EXIT_REALITY_PUBKEY

cat >"$HERE/.env" <<EOF
# Exit VM — generated by bootstrap.sh. Keep secret.
EXIT_SERVER_IP=$EXIT_SERVER_IP
EXIT_USER_UUID=$EXIT_USER_UUID
EXIT_SHORT_ID=$EXIT_SHORT_ID
EXIT_REALITY_PRIVKEY=$EXIT_REALITY_PRIVKEY
EXIT_REALITY_PUBKEY=$EXIT_REALITY_PUBKEY
EOF
chmod 600 "$HERE/.env"

log_info "rendering sing-box config"
mkdir -p "$HERE/cache"
render_template "$HERE/config/config.json.tmpl" "$HERE/config/config.json"
chmod 600 "$HERE/config/config.json"

open_port_443

log_info "starting sing-box"
(cd "$HERE" && docker compose up -d)

# Wait briefly and check the container is healthy.
sleep 2
if ! (cd "$HERE" && docker compose ps --status running | grep -q sing-box); then
  (cd "$HERE" && docker compose logs --tail 50 sing-box)
  die "sing-box failed to start"
fi

cat >"$HERE/deployment-info.txt" <<EOF
# Paste these into the Russia bootstrap:
EXIT_SERVER_IP=$EXIT_SERVER_IP
EXIT_REALITY_PUBKEY=$EXIT_REALITY_PUBKEY
EXIT_USER_UUID=$EXIT_USER_UUID
EXIT_SHORT_ID=$EXIT_SHORT_ID
EOF
chmod 600 "$HERE/deployment-info.txt"

log_ok "Exit VM is live on :443"
echo
echo "------- Russia bootstrap flags -------"
echo "sudo bash bootstrap.sh \\"
echo "  --exit-ip       $EXIT_SERVER_IP \\"
echo "  --exit-pubkey   $EXIT_REALITY_PUBKEY \\"
echo "  --exit-uuid     $EXIT_USER_UUID \\"
echo "  --exit-short-id $EXIT_SHORT_ID"
echo "--------------------------------------"
echo "(also saved to $HERE/deployment-info.txt)"
