#!/usr/bin/env bash
#
# Entrypoint for the vpn-exit image.
#
# First boot (fresh volume): generate Reality keypair + user UUID + short_id,
# detect public IP, write .env + deployment-info.txt, print the four handoff
# values the Russia container needs.
# Every boot: re-render /etc/sing-box/config.json and hand control to the
# PID-1 supervisor.

set -euo pipefail

# shellcheck source=../docker/common.sh
source /usr/local/lib/vpn/common.sh

VPN_STATE="/var/lib/vpn"
ENV_FILE="$VPN_STATE/.env"
INFO_FILE="$VPN_STATE/deployment-info.txt"
CONFIG_OUT="/etc/sing-box/config.json"
CONFIG_TMPL="/etc/vpn/config.json.tmpl"

mkdir -p "$VPN_STATE/cache"

print_handoff() {
  cat <<EOF

================= Russia bootstrap values =================
EXIT_IP=$EXIT_SERVER_IP
EXIT_PUBKEY=$EXIT_REALITY_PUBKEY
EXIT_UUID=$EXIT_USER_UUID
EXIT_SHORT_ID=$EXIT_SHORT_ID
===========================================================
(also saved to $INFO_FILE)
EOF
}

if [[ ! -f $ENV_FILE ]]; then
  log_info "=== first boot: generating exit-side secrets ==="

  log_info "generating Reality keypair"
  generate_reality_keypair
  EXIT_REALITY_PRIVKEY="$REALITY_PRIVKEY"
  EXIT_REALITY_PUBKEY="$REALITY_PUBKEY"
  EXIT_USER_UUID="$(generate_uuid)"
  EXIT_SHORT_ID="$(generate_short_id)"
  EXIT_SERVER_IP="${EXIT_PUBLIC_IP:-$(detect_public_ip)}"

  umask 077
  cat >"$ENV_FILE" <<EOF
# Exit VM — generated by entrypoint on first boot. Keep secret.
EXIT_SERVER_IP=$EXIT_SERVER_IP
EXIT_USER_UUID=$EXIT_USER_UUID
EXIT_SHORT_ID=$EXIT_SHORT_ID
EXIT_REALITY_PRIVKEY=$EXIT_REALITY_PRIVKEY
EXIT_REALITY_PUBKEY=$EXIT_REALITY_PUBKEY
EOF
  chmod 600 "$ENV_FILE"

  cat >"$INFO_FILE" <<EOF
# Paste these into the Russia container (env vars EXIT_IP / EXIT_PUBKEY / EXIT_UUID / EXIT_SHORT_ID).
EXIT_IP=$EXIT_SERVER_IP
EXIT_PUBKEY=$EXIT_REALITY_PUBKEY
EXIT_UUID=$EXIT_USER_UUID
EXIT_SHORT_ID=$EXIT_SHORT_ID
EOF
  chmod 600 "$INFO_FILE"

  print_handoff
else
  log_info "reusing existing $ENV_FILE (delete the volume to regenerate keys)"
  set -o allexport; # shellcheck disable=SC1091
  source "$ENV_FILE"
  set +o allexport
  print_handoff
fi

export EXIT_USER_UUID EXIT_REALITY_PRIVKEY EXIT_SHORT_ID
mkdir -p "$(dirname "$CONFIG_OUT")"
render_template "$CONFIG_TMPL" "$CONFIG_OUT"
chmod 600 "$CONFIG_OUT"

exec /usr/local/bin/vpn-supervisor
