#!/usr/bin/env bash
#
# Bootstraps the Russia (entry-hop) VM.
#
# Usage:
#   sudo bash bootstrap.sh \
#     --exit-ip       <EXIT_SERVER_IP>     \
#     --exit-pubkey   <EXIT_REALITY_PUBKEY> \
#     --exit-uuid     <EXIT_USER_UUID>      \
#     --exit-short-id <EXIT_SHORT_ID>
#
# Idempotent: re-running refreshes the config and restarts sing-box, but
# does not regenerate server keys unless you delete .env first.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=../scripts/common.sh
source "$REPO_ROOT/scripts/common.sh"

usage() {
  cat <<EOF
Usage: sudo bash bootstrap.sh \\
  --exit-ip       <ip>      \\
  --exit-pubkey   <pubkey>  \\
  --exit-uuid     <uuid>    \\
  --exit-short-id <short-id>
EOF
  exit 1
}

EXIT_SERVER_IP_ARG=""
EXIT_REALITY_PUBKEY_ARG=""
EXIT_USER_UUID_ARG=""
EXIT_SHORT_ID_ARG=""

while (($#)); do
  case "$1" in
    --exit-ip)        EXIT_SERVER_IP_ARG="$2";       shift 2;;
    --exit-pubkey)    EXIT_REALITY_PUBKEY_ARG="$2";  shift 2;;
    --exit-uuid)      EXIT_USER_UUID_ARG="$2";       shift 2;;
    --exit-short-id)  EXIT_SHORT_ID_ARG="$2";        shift 2;;
    -h|--help)      usage;;
    *) log_err "unknown arg: $1"; usage;;
  esac
done

require_root

log_info "=== Russia VM bootstrap ==="

install_docker
ensure_pkg gettext-base envsubst
ensure_pkg jq
ensure_pkg qrencode
ensure_pkg uuid-runtime uuidgen
ensure_pkg openssl
ensure_pkg curl

# Load existing .env first so CLI args override saved values only when passed.
if [[ -f $HERE/.env ]]; then
  log_info "reusing existing $HERE/.env (delete it to regenerate keys)"
  set -o allexport; # shellcheck disable=SC1091
  source "$HERE/.env"
  set +o allexport
fi

EXIT_SERVER_IP="${EXIT_SERVER_IP_ARG:-${EXIT_SERVER_IP:-}}"
EXIT_REALITY_PUBKEY="${EXIT_REALITY_PUBKEY_ARG:-${EXIT_REALITY_PUBKEY:-}}"
EXIT_USER_UUID="${EXIT_USER_UUID_ARG:-${EXIT_USER_UUID:-}}"
EXIT_SHORT_ID="${EXIT_SHORT_ID_ARG:-${EXIT_SHORT_ID:-}}"

for v in EXIT_SERVER_IP EXIT_REALITY_PUBKEY EXIT_USER_UUID EXIT_SHORT_ID; do
  [[ -n ${!v} ]] || { log_err "missing $v — pass it via --$(echo "$v" | tr '[:upper:]_' '[:lower:]-')"; usage; }
done

log_info "probing Exit VM at $EXIT_SERVER_IP:443"
if ! probe_tcp "$EXIT_SERVER_IP" 443; then
  log_warn "cannot reach $EXIT_SERVER_IP:443 — check firewall / exit VM is up before trusting this deploy"
else
  log_ok "Exit VM is reachable"
fi

# Generate RU-side server secrets only if we don't already have them.
if [[ -z ${RU_REALITY_PRIVKEY:-} || -z ${RU_REALITY_PUBKEY:-} ]]; then
  log_info "generating Russia-side Reality keypair"
  generate_reality_keypair
  RU_REALITY_PRIVKEY="$REALITY_PRIVKEY"
  RU_REALITY_PUBKEY="$REALITY_PUBKEY"
fi
: "${RU_SHORT_ID:=$(generate_short_id)}"
: "${RU_SERVER_IP:=$(detect_public_ip)}"

cat >"$HERE/.env" <<EOF
# Russia VM — generated by bootstrap.sh. Keep secret.
RU_SERVER_IP=$RU_SERVER_IP
RU_REALITY_PRIVKEY=$RU_REALITY_PRIVKEY
RU_REALITY_PUBKEY=$RU_REALITY_PUBKEY
RU_SHORT_ID=$RU_SHORT_ID
EXIT_SERVER_IP=$EXIT_SERVER_IP
EXIT_REALITY_PUBKEY=$EXIT_REALITY_PUBKEY
EXIT_USER_UUID=$EXIT_USER_UUID
EXIT_SHORT_ID=$EXIT_SHORT_ID
EOF
chmod 600 "$HERE/.env"

mkdir -p "$HERE/cache" "$HERE/users"
open_port_443

# Delegate the rest (user creation + render + up + print QR) to user.sh so
# there's one code path for "bring a user online".
log_info "creating initial admin user via user.sh"
bash "$HERE/user.sh" add admin --note "initial bootstrap user"

log_ok "Russia VM is live on :443"
echo
echo "Client QR and vless:// URI are printed above."
echo "To add more users later:  sudo ./user.sh add <name>"
