#!/usr/bin/env bash
#
# Entrypoint for the vpn-russia image.
#
# First boot (fresh volume): generate Russia Reality keypair, write .env,
# create the initial admin user, render config, print QR + vless:// URI.
# Every boot: re-render /etc/sing-box/config.json from .env + users/ and
# hand control to the PID-1 supervisor that runs sing-box.
#
# Required env vars on first boot (not needed afterwards — persisted to .env):
#   EXIT_IP         public IP of the exit VM
#   EXIT_PUBKEY     Reality public key printed by the exit container
#   EXIT_UUID       UUID printed by the exit container
#   EXIT_SHORT_ID   short_id printed by the exit container
#
# Optional:
#   INITIAL_USER    name of the first user (default "admin")
#   RU_PUBLIC_IP    override the auto-detected public IP

set -euo pipefail

# shellcheck source=../docker/common.sh
source /usr/local/lib/vpn/common.sh

VPN_STATE="/var/lib/vpn"
ENV_FILE="$VPN_STATE/.env"

mkdir -p "$VPN_STATE/users" "$VPN_STATE/domains" "$VPN_STATE/cache"

die_missing_exit_params() {
  cat >&2 <<EOF
${_c_red}[err ]${_c_reset} missing EXIT_* env vars.

This is a fresh volume — the Russia container needs the four handoff values
produced by the exit container's first boot. Deploy exit/ first, capture its
deployment-info.txt, then (re)run this container with:

  docker run ... \\
    -e EXIT_IP=<exit public IPv4> \\
    -e EXIT_PUBKEY=<reality public key> \\
    -e EXIT_UUID=<user uuid> \\
    -e EXIT_SHORT_ID=<short_id> \\
    vpn-russia

(Or populate russia/.env with those four values and use docker compose.)
EOF
  exit 1
}

if [[ ! -f $ENV_FILE ]]; then
  log_info "=== first boot: generating Russia-side secrets ==="

  : "${EXIT_IP:=}"
  : "${EXIT_PUBKEY:=}"
  : "${EXIT_UUID:=}"
  : "${EXIT_SHORT_ID:=}"
  for v in EXIT_IP EXIT_PUBKEY EXIT_UUID EXIT_SHORT_ID; do
    [[ -n ${!v} ]] || die_missing_exit_params
  done

  log_info "probing exit VM at $EXIT_IP:443"
  if probe_tcp "$EXIT_IP" 443; then
    log_ok "exit VM is reachable"
  else
    log_warn "cannot reach $EXIT_IP:443 — check firewall / exit VM is up before trusting this deploy"
  fi

  log_info "generating Russia Reality keypair"
  generate_reality_keypair
  RU_REALITY_PRIVKEY="$REALITY_PRIVKEY"
  RU_REALITY_PUBKEY="$REALITY_PUBKEY"
  RU_SHORT_ID="$(generate_short_id)"
  RU_SERVER_IP="${RU_PUBLIC_IP:-$(detect_public_ip)}"

  umask 077
  cat >"$ENV_FILE" <<EOF
# Russia VM — generated by entrypoint on first boot. Keep secret.
RU_SERVER_IP=$RU_SERVER_IP
RU_REALITY_PRIVKEY=$RU_REALITY_PRIVKEY
RU_REALITY_PUBKEY=$RU_REALITY_PUBKEY
RU_SHORT_ID=$RU_SHORT_ID
EXIT_SERVER_IP=$EXIT_IP
EXIT_REALITY_PUBKEY=$EXIT_PUBKEY
EXIT_USER_UUID=$EXIT_UUID
EXIT_SHORT_ID=$EXIT_SHORT_ID
EOF
  chmod 600 "$ENV_FILE"

  vpn init-admin "${INITIAL_USER:-admin}"
  log_ok "Russia entry hop is ready"
else
  log_info "reusing existing $ENV_FILE (delete the volume to regenerate keys)"
  vpn render
fi

exec /usr/local/bin/vpn-supervisor
